<a href="https://colab.research.google.com/github/vsnupoudel/Vertex-AI-EndtoEnd/blob/main/gcp_vertex_on_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install google-cloud google-cloud-aiplatform google-cloud-storage

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting google-cloud
  Downloading google_cloud-0.34.0-py2.py3-none-any.whl (1.8 kB)
Collecting google-cloud-aiplatform
  Downloading google_cloud_aiplatform-1.18.3-py2.py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 6.7 MB/s
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.7/dist-packages (2.5.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-aiplatform) (1.22.1)
Requirement already satisfied: packaging<22.0.0dev,>=14.3 in /usr/local/lib/python3.7/dist-packages (from google-cloud-aiplatform) (21.3)
Collecting google-cloud-bigquery<3.0.0dev,>=1.15.0
  Downloading google_cloud_bigquery-2.34.4-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 53.6 MB/s
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /usr/local/lib/python3.7/dist-packages (from google-cloud-aiplatform) (3.19.6)
Collecting google-cloud-resource-manager<3.0.0dev,>=1.3.3
  Downloading google_cloud_resource_manager-1.6.3-py2.py3-none-any.whl (233 kB)
     |████████████████████████████████| 233 kB 62.2 MB/s
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-aiplatform) (2.8.2)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-storage) (2.23.0)
Requirement already satisfied: google-resumable-media>=2.3.2 in /usr/local/lib/python3.7/dist-packages (from google-cloud-storage) (2.4.0)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-storage) (2.14.1)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-storage) (2.3.2)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.56.4)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.50.0)
Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.48.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (0.2.8)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (1.15.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.8.2)
Collecting grpc-google-iam-v1<1.0.0dev,>=0.12.4
  Downloading grpc_google_iam_v1-0.12.4-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.7/dist-packages (from google-resumable-media>=2.3.2->google-cloud-storage) (1.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging<22.0.0dev,>=14.3->google-cloud-aiplatform) (3.0.9)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage) (0.4.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2.10)
Installing collected packages: grpc-google-iam-v1, google-cloud-resource-manager, google-cloud-bigquery, google-cloud-aiplatform, google-cloud
  Attempting uninstall: google-cloud-bigquery
    Found existing installation: google-cloud-bigquery 3.3.6
    Uninstalling google-cloud-bigquery-3.3.6:
      Successfully uninstalled google-cloud-bigquery-3.3.6
Successfully installed google-cloud-0.34.0 google-cloud-aiplatform-1.18.3 google-cloud-bigquery-2.34.4 google-cloud-resource-manager-1.6.3 grpc-google-iam-v1-0.12.4

In [4]:
from google.colab import auth
auth.authenticate_user()

In [1]:
import datetime
import os
import time

import numpy as np
import pandas as pd
import tensorflow as tf

from google.cloud import aiplatform, storage
from google.cloud.aiplatform import gapic as aip
from sklearn.preprocessing import StandardScaler

In [2]:
# Enter your project, region, and a bucket name. Then run the  cell to make sure the
# Cloud SDK uses the right project for all the commands in this notebook.

PROJECT = 'starry-embassy-363916' # REPLACE WITH YOUR PROJECT ID
BUCKET = 'starry-embassy-363916-time-series01' # REPLACE WITH A UNIQUE REGIONAL BUCKET NAME e.g. your PROJECT NAME
REGION = 'us-central1' # REPLACE WITH YOUR BUCKET REGION e.g. us-central1
BUCKET_URI = 'gs://' + BUCKET

#Don't change the following command - this is to check if you have changed the project name above.
assert PROJECT != 'your-project-name', 'Don''t forget to change the project variables!'

In [3]:
# Initialize the Vertex SDK for Python
aiplatform.init(project=PROJECT, location=REGION, staging_bucket=BUCKET)

In [4]:
from google.cloud import bigquery

# project = 'starry-embassy-363916' # Project ID inserted based on the query results selected to explore
# location = 'us-central1' # Location inserted based on the query results selected to explore
client = bigquery.Client(project=PROJECT, location=REGION)

In [5]:
# Perform a query.
# QUERY = ("SELECT * FROM `starry-embassy-363916.bitcoin_db.forex_distinct`")
# query_job = client.query(QUERY)  # API request
# rows = query_job.result().to_dataframe()  # Waits for query to finish

In [13]:
rows = pd.read_csv('rows.csv', index_col=0)
rows.shape

(22243, 3)

In [14]:
rows.head(4)

                  Close_Time   Close_Price  Week_Number
0  2022-08-26 12:20:00+00:00  21242.369141           34
1  2022-08-26 12:25:00+00:00  21258.070312           34
2  2022-08-26 12:30:00+00:00  21468.148438           34
3  2022-08-26 12:35:00+00:00  21520.556641           34

In [15]:
# rows.to_csv('rows.csv')

# Train using Vertex AI

In [16]:
aiplatform.init(
    # your Google Cloud Project ID or number
    # environment default used is not set
    project=PROJECT,

    # the Vertex AI region you will use
    # defaults to us-central1
    location=REGION,

    # Google Cloud Storage bucket in same region as location
    # used to stage artifacts
    staging_bucket= BUCKET,

    # custom google.auth.credentials.Credentials
    # environment default creds used if not set
    # credentials=my_credentials,

    # customer managed encryption key resource name
    # will be applied to all Vertex AI resources if set
    # encryption_spec_key_name=my_encryption_key_name,

    # the name of the experiment to use to track
    # logged metrics and parameters
    # experiment='bitcoin from 0826-1113',

    # description of the experiment above
    # experiment_description='bitcoin from 0826-1113, using a dynamic view as dataset'
)

In [18]:
# DATASET_ID = '8535642906843676672'
# # dataset = 
# aiplatform.TabularDataset(dataset_name='8535642906843676672')
 #('projects/{0}/location/{1}/datasets/{2}'.format(PROJECT, REGION, DATASET_ID))

In [19]:
# job = aiplatform.AutoMLTabularTrainingJob(
#   display_name="train-automl",
#   optimization_prediction_type="regression",
#   optimization_objective="minimize-rmse",
# )

## Can't be done in vertexAI api for time series. training in colab.

In [20]:
# !pip install pmdarima

In [21]:
# from pmdarima.arima import auto_arima

In [22]:
model = aiplatform.Model('3264683119332032512')

In [27]:
QUERY = ("SELECT * FROM `starry-embassy-363916.bitcoin_db.two_and_half_hour_bitcoin`")
query_job = client.query(QUERY)  # API request
pdf = query_job.result().to_dataframe()  # Waits for query to finish
pdf

                  Close_Time   Close_Price  Week_Number
0  2022-11-13 20:25:00+00:00           NaN            1
1  2022-11-13 20:20:00+00:00           NaN            1
2  2022-11-13 20:15:00+00:00           NaN            1
3  2022-11-13 20:10:00+00:00           NaN            1
4  2022-11-13 20:05:00+00:00           NaN            1
5  2022-11-13 20:00:00+00:00           NaN            1
6  2022-11-13 19:55:00+00:00  16545.134766            1
7  2022-11-13 19:50:00+00:00  16548.755859            1
8  2022-11-13 19:45:00+00:00  16549.945312            1
9  2022-11-13 19:40:00+00:00  16546.210938            1
10 2022-11-13 19:35:00+00:00  16550.277344            1
11 2022-11-13 19:30:00+00:00  16547.890625            1
12 2022-11-13 19:25:00+00:00  16548.439453            1
13 2022-11-13 19:20:00+00:00  16520.158203            1
14 2022-11-13 19:15:00+00:00  16507.830078            1
15 2022-11-13 19:10:00+00:00  16512.410156            1
16 2022-11-13 19:05:00+00:00  16513.371094            1
17 2022-11-13 19:00:00+00:00  16526.994141            1
18 2022-11-13 18:55:00+00:00  16504.875000            1
19 2022-11-13 18:50:00+00:00  16502.560547            1
20 2022-11-13 18:45:00+00:00  16505.951172            1
21 2022-11-13 18:40:00+00:00  16497.601562            1
22 2022-11-13 18:35:00+00:00  16493.177734            1
23 2022-11-13 18:30:00+00:00  16486.980469            1
24 2022-11-13 18:25:00+00:00  16500.744141            1
25 2022-11-13 18:20:00+00:00  16518.921875            1
26 2022-11-13 18:15:00+00:00  16529.046875            1
27 2022-11-13 18:10:00+00:00  16545.751953            1
28 2022-11-13 18:05:00+00:00  16563.361328            1
29 2022-11-13 18:00:00+00:00  16564.242188            1
30 2022-11-13 17:55:00+00:00  16565.763672            1
31 2022-11-13 17:50:00+00:00  16562.234375            1
32 2022-11-13 17:45:00+00:00  16552.599609            1
33 2022-11-13 17:40:00+00:00  16557.533203            1
34 2022-11-13 17:35:00+00:00  16526.621094            1
35 2022-11-13 17:30:00+00:00  16509.414062            1
36 2022-11-13 17:25:00+00:00  16533.804688            1
37 2022-11-13 17:20:00+00:00  16526.404297            1
38 2022-11-13 17:15:00+00:00  16517.314453            1
39 2022-11-13 17:10:00+00:00  16571.894531            1
40 2022-11-13 17:05:00+00:00  16579.718750            1
41 2022-11-13 17:00:00+00:00  16578.906250            1
42 2022-11-13 16:55:00+00:00  16584.904297            1
43 2022-11-13 16:50:00+00:00  16585.976562            1
44 2022-11-13 16:45:00+00:00  16571.285156            1
45 2022-11-13 16:40:00+00:00  16553.820312            1
46 2022-11-13 16:35:00+00:00  16562.578125            1
47 2022-11-13 16:30:00+00:00  16568.962891            1
48 2022-11-13 16:25:00+00:00  16550.777344            1
49 2022-11-13 16:20:00+00:00  16554.550781            1
50 2022-11-13 16:15:00+00:00  16567.949219            1
51 2022-11-13 16:10:00+00:00  16580.269531            1
52 2022-11-13 16:05:00+00:00  16575.271484            1
53 2022-11-13 16:00:00+00:00  16577.556641            1
54 2022-11-13 15:55:00+00:00  16565.251953            1
55 2022-11-13 15:50:00+00:00  16571.886719            1

In [26]:
!gcloud storage cp gs://starry-embassy-363916-time-series01/aiplatform-2022-10-29-12:12:28.328-aiplatform_custom_trainer_script-0.1.tar.gz .

Copying gs://starry-embassy-363916-time-series01/aiplatform-2022-10-29-12:12:28.328-aiplatform_custom_trainer_script-0.1.tar.gz to file://./aiplatform-2022-10-29-12:12:28.328-aiplatform_custom_trainer_script-0.1.tar.gz

In [ ]:
model.batch_predict()